### ISSUE TITLE
[Whitepaper][200 USD] Chinese TON white paper review/TON 中文白皮书修订版

### ISSUE THREAD

**Issue by Arno-Zhang** [TONCommunity/ton-tier-0-program#1]
**About This Project**
Tier 0 program 意图通过赏金的方式吸引社区成员参与项目。任何人都可以发布 Tier 0 program 任务，但需要尊从我们的发布[标准和格式。](https://github.com/TONCommunity/ton-tier-0-program/blob/master/template.md)。这条 program 作为示例，演示社区应该如何参与，并获取赏金。
正文：白皮书是一个项目的立足点，由 Tooz wu 翻译的初版 TON 中文白皮书，在中文加密世界引起广泛影响。随着项目在开发者和投资者之间的传播，越来越多人关注 TON 底层技术。而社区版 TON 基于原 TON 白皮书的底层技术需要更进一步修正。所以发布此 Tier 0 program，征集翻译人员对初版TON白皮书做完全修正，以飨读者。
参与 Tier 0 program 需要掌握英文语言，所以本文档也中英混合，敬请理解。
> The difficulty level of this bounty is estimated as **DIFFICULTY**. The reward for completion of this project is set at **$200** (paid in TON💎).

_Requirements for completion:_
- Correct the full text to ensure that all text conforms to the characteristics of the Chinese language. It is easy for developers to understand.

_Necessary Skills:_
- Chinese language skills
- English language skills

**Applying For This Project**

To apply for this project, please read more about the process below before leaving a comment with the following:

1. A brief proposal relating to the project (e.g. Your experience, how you wish to approach the project, estimated time to completion etc.)
2. Your name and a contact email address (or another form of contact, eg. Telegram username)

**The Process**

Applicants will only be permitted to participate in one Tier 0 project at any one time. You can apply for as many projects as you like, but will not be eligible to be accepted until your open projects have been completed. In the meantime the projects may be awarded to other available applicants.

If your application for the project is successful we’ll contact you using the details you provided, assign the project to you and mark it as in progress. You’ll be required to check in regularly with the TONCommunity.org admin to discuss progress and development. We’ll also use these updates to ensure that the PR is being completed to a satisfactory standard. If we determine that the project isn’t being completed to a satisfactory standard and that this cannot be achieved with minor amends or within a satisfactory timeframe, we hold the right to dismiss the PR and reopen the project to other applicants.

To deliver the project your PR must be submitted to the respective repo. TONCommunity.org repo maintainers will then leave comments and request amends if necessary. After you’ve submitted your project, we’ll review against the brief to ensure it meets the criteria and deliverables.

Once your project is approved as complete a member of the TONCommunity.org admin will follow up to discuss payment. You’ll need to submit an invoice and payment will be issued in (💎) TON (equivalent to the USD reward value assigned to the project), sent to an address of your choosing. We may need to request additional information regarding your identity in order to comply with our own internal Know Your Customer (KYC) guidelines.

_If you’re unsuccessful in applying for this particular project, please consider applying for others. Thanks for your interest and good luck with your application!_

**Comment by ecrivaine** [comment]
Hi~ This is Erica, a crypto enthusiast and science writer. I‘ve already completed the Chinese translation of the TON white paper with my friends lucas3s, Inkiy and CryptoRose. You can read the new Chinese version of the WP here: https://github.com/ecrivaine/ton-chinese-whitepaper.

**Comment by toozwu** [comment]
Merged. https://github.com/TONCommunity/ton-chinese-whitepaper
